stages:
  - build # dependancies
  - pester # pester test script
  - test_pwsh # test powershell core latest
  - test_powershell # test powershell
  - deploy_psprivate # deploy to psgallary private instance
  - deploy_psgallary # deploy to psgallary
build-job
  stage: build
  tags:
    - pwsh
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
pester-job:
  stage: pester
  tags:
    - pwsh
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
test-pwsh-job:
  stage: test_pwsh
  tags:
    - pwsh
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
test-powershell-job:
  stage: test_powershell
  tags:
    - pwsh
  script:
    - powershell.exe
    - write-host -f green "template ci\cd config successfull"
psgallary-deploy-job:
  stage: deploy_psgallary
  tags:
    - pwsh
  script:
    - pwsh.exe
psprivate-deploy-job:
  stage: deploy_psprivate
  tags:
    - pwsh
  script:
    - pwsh.exe
    - .\build\bt6-ci-deploy-psgallary.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "deploylocal" && $CI_BUILD_STATUS == "success"'

# Create Release Stage
create_release:
  stage: release
  tags:
    - windows
  script: 
    - pwsh.exe
    - Compress-Archive -Path .\ -DestinationPath Build.gz
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "deploy" && $CI_BUILD_STATUS == "success"'
  artifacts:
    paths:
      - Build.gz
      - ./dist/*

# Deploy Coverage to Coverails.io Stage
deploy_coverage:
  stage: release
  tags:
    - windows
  script:
    - pwsh.exe
    - .\bt8-ci-deploy-coveralls-report.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "deploy" && $CI_BUILD_STATUS == "success"'

