stages:
  - test
  - build
  - deploy

build-job:
  stage: test
  tags:
    - pwsh
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
pester-job:
  stage: build
  tags:
    - pwsh
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
test-pwsh-job:
  stage: deploy
  tags:
    - pwsh
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"